disabled_rules: # rule identifiers to exclude from running
- line_length
- force_cast
- shorthand_operator
- type_body_length
- legacy_constructor
- function_parameter_count
excluded:
- Pods
function_body_length:
    warning: 55
    error: 100
file_length:
    warning: 550
    error: 1000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 17
    error: 25
